// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpFAYhmiWPHs6_155FB_82x3IQRV-Afp0',
    appId: '1:963135160044:web:0b760541b3667cfa61efc9',
    messagingSenderId: '963135160044',
    projectId: 'tracker-42032',
    authDomain: 'tracker-42032.firebaseapp.com',
    storageBucket: 'tracker-42032.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoF1jvvjIWYPLXN5mCFvDuaQrwYKftVCo',
    appId: '1:963135160044:android:5f77b788a0c1f07261efc9',
    messagingSenderId: '963135160044',
    projectId: 'tracker-42032',
    storageBucket: 'tracker-42032.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOaWeQ-X_-K2ho1QKji_fRI5nmrcQG4sA',
    appId: '1:963135160044:ios:4bab772dfcd54b4c61efc9',
    messagingSenderId: '963135160044',
    projectId: 'tracker-42032',
    storageBucket: 'tracker-42032.appspot.com',
    iosBundleId: 'com.example.mobileTrackerTwo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOaWeQ-X_-K2ho1QKji_fRI5nmrcQG4sA',
    appId: '1:963135160044:ios:a16c6e281dbc080961efc9',
    messagingSenderId: '963135160044',
    projectId: 'tracker-42032',
    storageBucket: 'tracker-42032.appspot.com',
    iosBundleId: 'com.example.mobileTrackerTwo.RunnerTests',
  );
}
